TheOdinProject/javascript_curriculum

- JS101/code-structure.md
- JS101/final-project.md
- JS101/first-steps.md
- JS101/javascript-dev-tools.md
- JS101/running-javascript.md
- JS101/what-the-javascript.md
A quick first pass, I put some links for things we've made that are similar to what you'd written.
> some things weve already made that might help

- JS101/DOM-manipulation.md
A starting point for the DOM lesson. It's pretty text heavy/hard on the eyes.
> Dom manipulation

- JS101/JS_resources.md
- JS101/code-structure.md
- MoreJS/testing.md
I didn't see anything like this.  here's our initial list of resources and exercises.  
Javascript.info is exceptional
here's a longer list of general resources we've been collecting you may want to look through.  maybe there's a couple you haven't found yet
https://github.com/EliumAcademy/Sepco/wiki/3-General-Resources
> added resource and exercise file to 101

- MoreJS/APIs.md
- MoreJS/promises-async.md
I've gone through and proofread some of the documents per Issue #31.
Documents updated with minor grammar changes:
- `/MoreJS/APIs.md`
- `/MoreJS/promises-async.md`
> Fix Grammar Issues

- JS101/fundamentals-1.md
While 'Loose' or even 'Weak' would work, I feel that 'Dynamic' is more correct and precise.
> Change 'Loose' to 'Dynamic'

- JS101/DOM-manipulation.md
> DOM-Manipulation.md

- JS101/fundamentals-2.md
The w3schools lesson makes mention of switch statements but doesn't go into them, so I added one.
> Add link to a switch tutorial

- JS101/fundamentals-1.md
With honest disagreement of different style guides regarding the use of `const` and `let`, I changed the definitions to be style neutral.
> Modify "Variable" definition and add "Scope" line

- MoreJS/organizing-js/objects-constructors.md
The word function does not describe the code example below
> Changes function to program

- JS101/DOM-manipulation.md
- JS101/fundamentals-2.md
- JS101/fundamentals-3.md
Made edits to my previous commits and wrote Points to Ponder section for JS101/fundamentals-3
> fundamentals-3 points to ponder, edits to previous PtP

- JS101/etch-a-sketch-project.md
Just thought I'd contribute and add my solution to the Etch-a-Sketch project!
> Add my Etch-A-Sketch project solution

- JS101/fundamentals/rock-paper-scissors-project.md
Added my solution to the Rock Paper Scissors project.
Constructive comments/critique welcome :]
> Add solution to rock-paper-scissors-project.md

- organizing-js/objects-constructors.md
Add a link to allow students to view the fundamentals of JS objects before they dive deeper in the JS track on the object and object constructor page.
> add link for basic object course in 101

- JS101/fundamentals/rock-paper-scissors-project.md
My solution to Rock, Paper Scissors project.
> Rock Paper Scissors Solution

- JS101/etch-a-sketch-project.md
> add my solution to the list

- JS101/final-project.md
thanks for the content as usual, I really enjoyed this project.
> add my calculator project to the solutions list

- JS101/etch-a-sketch-project.md
Does what it says on the package!
> Added my example of the etch-a-sketch problem

- JS101/fundamentals/fundamentals-1.md
I dunno much javascript so someone please review if I correctly extracted the most important information/takeaways.
Some things I didn't question about that were in the reading:
* Let/Const > Var, for modern JS practices
* being able to declare numbers with/without decimals/scientific notation
* numbers are primitive values
* floating point arithmetic is not always accurate
* NaN
* Infinity
* isNaN(x);
* Hexadecimal
* typeof(x)
* Unary vs Binary Operators
* Chaining Assignments
* Comma Operator
> Proposed Learning Outcomes for Fundamentals 1

- JS101/etch-a-sketch-project.md
- JS101/final-project.md
- JS101/fundamentals/rock-paper-scissors-project.md
I updated my repo structure and had to fix the broken links to my solutions. The merge conflicts come from the project changes. New links were appended by git. I didn't pull the upstream before committing, sorry. 
I only updated my own links, I didn't touch any of the content nor the links to projects of other users while fixing the merge conflicts.
> Update my solution links

- JS101/fundamentals/rock-paper-scissors-project.md
add my rock paper scissors solution for a game in the console.
> add nick leake solution

- JS101/final-project.md
Pull request to add my solution to final-project.md
> Added my solution

- JS101/fundamentals/rock-paper-scissors-project.md
completed rock paper scissors gui version
> Solution to gui version of rock paper scissors project

- JS101/fundamentals/rock-paper-scissors-project.md
Please add my rock/paper/scissors solution to students solutions.Thanks!
> my rock paper scissors solution.

- JS101/etch-a-sketch-project.md
add me to the student solutions.
> Etch-a-sketch my solution.

- JS101/fundamentals/rock-paper-scissors-project.md
Hi! I would like to add my project solution about the Rock-Paper-Scissors game
> K.Wagner Rock-Paper-Scissors game

- JS101/fundamentals/rock-paper-scissors-project.md
Hi! I would like to add my solution of the Rock-Paper-Scissors project.
> Added Alexey Leonov's solution

- JS101/fundamentals/rock-paper-scissors-project.md
> added my project

- JS101/fundamentals/rock-paper-scissors-project.md
Added a new link about my project
> update my project

- JS101/final-project.md
Hi all, added a new calculator thingy
> added SamJamCul's version of calculator

- JS101/fundamentals/rock-paper-scissors-project.md
I've been using the simple way of adding my solutions directly on git so this time around, i made use of the more proper way.
> Added the link to my solution to the rock-paper_scissors-project.md file

- JS101/fundamentals/rock-paper-scissors-project.md
Reverts TheOdinProject/javascript_curriculum#171
My project is incomplete
> Revert "Submitting my project"

- JS101/fundamentals/rock-paper-scissors-project.md
Hi,
Just completed the Rock Paper Scissors project. Hope its up to par!
Cheers,
Brad
> new completed project

- JS101/etch-a-sketch-project.md
> added my project.

- JS101/fundamentals/rock-paper-scissors-project.md
Hi! 
I would like to add my updated Rock-Paper-Scissors project to your list of projects. I hope everything was done correctly :)
Cheers,
Kerstin
> Updated Rock-Paper-Scissors, K.Wagner's project was added

- JS101/fundamentals/rock-paper-scissors-project.md
Hey,
Finally finished a half-decent UI.
Cheers,
Brad
> new RPS project added

- JS101/etch-a-sketch-project.md
Please add this solution to the Web development 101, Ethc-a-Sketch solutions list.
> Add Clifford Mink's solution to Etch-a-sketch project

- JS101/fundamentals/rock-paper-scissors-project.md
Add my solution to the javascript exercise.
> Add my solution to the exercise

- async-apis/project.md
Here is my weather app solution for the async-apis section of the Javascript Curriculum. This is my first git pull request so let me know if there's anything I need to do differently.
> Adding my Project

- organizing-js/library-project.md
> Javascript Project: Library - Add my solution.

- JS101/etch-a-sketch-project.md
Dear Project Maintainer,
please add my solution to the etch-a-sketch exercise.
Thank you and have a great day!
> Etch-a-sketch solution

- JS101/etch-a-sketch-project.md
Hi,
I've just finish the project. :smile:
> Add Uy Binh' solution

- JS101/etch-a-sketch-project.md
Hello! I've added my solution to the etch-a-sketch project page.
> added hypnagogiasmic's solution to etch-a-sketch project page

- JS101/fundamentals/rock-paper-scissors-project.md
Contribution to rock-paper-scissors file
> Add Almyra's solution

- organizing-js/restaurant-project.md
This is my submission for this assignment.  It was a great opportunity to start to use webpack and ES6 modules.  It also gave me a chance to practice some CSS grid too!  Hope you like it!
> Submit rpalo's solution to the restaurant project

- JS101/final-project.md
My solution link for webdev101 javascript final project: Calculator
> added solution

- JS101/fundamentals/rock-paper-scissors-project.md
Added Adrien Pardo's solution.
> Added Adrien Pardo's solution

- JS101/fundamentals/rock-paper-scissors-project.md
> add my project

- JS101/fundamentals/rock-paper-scissors-project.md
Easter Egg: Added functionality that keeps track of how many times the player picked rock/paper/scissors/other. Special message at the end if any of those counts is at 5.
> Add Natalie's Aldrich solution

- JS101/fundamentals/fundamentals-1.md
because (4 + 6 + 9) / 77 = 0.24675324675324675
> fixed minor error

- JS101/fundamentals/rock-paper-scissors-project.md
Added rock-paper-scissor solution, please pull thanks.
> added my rock-paper-scissor project solution

- JS101/fundamentals/rock-paper-scissors-project.md
> Added my solution of rockpaperscissors game

- JS101/etch-a-sketch-project.md
- JS101/fundamentals/rock-paper-scissors-project.md
> fixed rock paper scissor link and added etch-a-sketch solution

- JS101/etch-a-sketch-project.md
> Added solution of Etch-a-Sketch

- JS101/fundamentals/rock-paper-scissors-project.md
I have added my contribution and link to the project list.
> Added my repository to the list

- async-apis/project.md
- js-rails/project_rails_backend.md
- organizing-js/project.md
- organizing-js/restaurant-project.md
- organizing-js/tic-tac-toe-project.md
- project_final_js.md
> Fix/add links to GitHub repo for student solutions

- JS101/fundamentals/rock-paper-scissors-project.md
add my solution to student solution section
> add my solution

- JS101/fundamentals/rock-paper-scissors-project.md
added link to view Lee Rogers's UI version in browser
> added link to view in browser

- JS101/fundamentals/rock-paper-scissors-project.md
Add my solution to the Rock Paper Scissors exercise
> Add my solution to the Rock Paper Scissors exercise

- JS101/fundamentals/rock-paper-scissors-project.md
Adding my rock paper scissors project here
> Adding my own project

- JS101/fundamentals/rock-paper-scissors-project.md
[Click here to view solution](https://github.com/NicholasEwing/rock-paper-scissors)
> Added Nicholas Ewing's solution.

- JS101/etch-a-sketch-project.md
I have added the line (including links).
> Please add my (Simon Tharby's) solution to the list. Thanks!

- JS101/etch-a-sketch-project.md
Please add my solution to the Odin etch-a-sketchpad project.
> add sketchpad for Augusto Del Valle

- JS101/etch-a-sketch-project.md
> Add Jarred Herrington's solution

- JS101/fundamentals/rock-paper-scissors-project.md
Trying my first ever pull request to add my solution to the rock-paper-scissors game. Please email me if something went wrong.
Thanks!
Allan
> Add Allan Burns' solution to rock-paper-scissors-project.md.

- JS101/fundamentals/rock-paper-scissors-project.md
Added Daniel Mau's solution to the solution list
> Added Daniel Mau's solution to the solution list

- JS101/fundamentals/rock-paper-scissors-project.md
Added link to my gui solution for the rock, paper, scissors project and fixed a broken link to my console solution.
> Added GUI solution for rock-paper-scissors project

- JS101/fundamentals/rock-paper-scissors-project.md
Fabricio Garcia's solution rock-paper-scissors
> Fabricio Garcia's solution rock-paper-scissors

- JS101/etch-a-sketch-project.md
Includes an option to change to colors.
> Add Natalie Aldrich's Solution

- JS101/etch-a-sketch-project.md
Request to add my solution to the curriculum
> my solution

- JS101/fundamentals/rock-paper-scissors-project.md
Not sure what to write here, the other curriculum repo had a template.
> Add solution to rock paper scissors project

- JS101/fundamentals/rock-paper-scissors-project.md
> add Patrick McGranaghan's repo

- JS101/javascript-dev-tools.md
I noticed this resource is also an assignment in the [first dev tools](https://www.theodinproject.com/courses/web-development-101/lessons/developer-tools) lesson so its redundant here. 
Also the Wes Bos additional resource was really neat :D
> Remove Repeated Resource

- JS101/fundamentals/rock-paper-scissors-project.md
Added my rock-paper-scissors game
> Added gui rock-paper-scissors game

- JS101/fundamentals/rock-paper-scissors-project.md
I just completed the rock paper scissors assignment and I wish to have my solution on the list. Thank you.
> Added Josiah Lawrence's rock paper scissors link

- JS101/fundamentals/rock-paper-scissors-project.md
Wrangling git to make this submission was much more involved than the actual game implementation!
> Add Joe Collins' RPS implementation

- async-apis/async-await.md
- async-apis/project.md
Please let me know if you see any typos or if something could be written better!
> adds async-await lesson

- async-apis/async-await.md
adds newlines around code blocks
> fixes formatting

- async-apis/APIs.md
relative path wasn't working so i added the full path.
> Added missing image issue #496

- async-apis/APIs.md
As seen on [this page](https://www.theodinproject.com/courses/javascript/lessons/working-with-apis), under 'CORS'
> fixes broken markdown

- JS101/final-project.md
> Adding finished calculator project

- JS101/fundamentals/rock-paper-scissors-project.md
Add my solution of the project to the page.
> Adding my solution

- JS101/etch-a-sketch-project.md
> Adding my solution of the project

- JS101/fundamentals/rock-paper-scissors-project.md
Added contribution to Rock-Paper-Scissors
> Added contribution to Rock-Paper-Scissors

- frameworks/frameworks-project.md
look at me.. i can make a project
> add project

- JS101/final-project.md
> Added my JS101 final project - calculator

- JS101/fundamentals/rock-paper-scissors-project.md
Adds my rock-paper-scissors solution. Please let me know if I need to make any changes before getting this merged, thanks! 
-Isaac Orme
> Adds isaacs rps solution

- frameworks/angular.md
- frameworks/frameworks-project.md
- frameworks/react-introduction.md
Also added consistent spacing between headers and paragraph, sorry for OCD 😅
> Fix assignment header in framework project

- JS101/fundamentals/rock-paper-scissors-project.md
manmohan's solution to the project rock, paper, scissors.
> added manmohan's solution

- JS101/code-structure.md
Change 'Your Assignment' to 'Assignment' to keep consistency, as referenced in https://github.com/TheOdinProject/theodinproject/issues/909
> Change 'Your Assignment' to 'Assignment'

- frameworks/vue.md
> Fix additional resources header in vue lesson

- JS101/fundamentals/rock-paper-scissors-project.md
Please add my solution to the bottom of the rock, paper, scissors project page. Thanks!
> Add Brian Giordano's solution to end of list

- frameworks/frameworks-project.md
This is a simple ReactJS book library app.
> Add my solution to framework project

- JS101/fundamentals/rock-paper-scissors-project.md
[Ode Akugbe's Solution](https://github.com/Blaize3/rock-paper-scissors) - [View in Browser](https://blaize3.github.io/rock-paper-scissors/index.html)
> Please kindly upload my solution

- JS101/fundamentals/rock-paper-scissors-project.md
Hi there, looking to add my solution to the page.
> adding student solution

- JS101/fundamentals/rock-paper-scissors-project.md
Add my Rock-Paper-Scissors project
> Add my Rock-Paper-Scissors project

- organizing-js/project.md
Co-authored-by: Kyle Lemon <james.kyle.lemon@gmail.com>
> Added Kyle and Paul's Solution

- organizing-js/factory-functions.md
A revision to be reviewed to the JS curriculum.
> Change Player factory to make it a working example

- JS101/etch-a-sketch-project.md
- JS101/final-project.md
- JS101/fundamentals/rock-paper-scissors-project.md
please add my solution to final project, as linked in JS101/final-project.md
> my solution to final project

- JS101/fundamentals/rock-paper-scissors-project.md
added my solution to the markdown file
> Added terrancebee solution

- JS101/etch-a-sketch-project.md
Adding my solution to the etch-a-sketch project page
> add my student solution link

- JS101/etch-a-sketch-project.md
> updated the file with my project

- JS101/etch-a-sketch-project.md
Minimal CSS Formatting -- May add more in future update
> Add Brendaneus' Solution to Student List

- JS101/fundamentals/rock-paper-scissors-project.md
Add my Rock-Paper-Scissors project updated from console based to a UI version
> Add my Updated project with UI design

- JS101/etch-a-sketch-project.md
Add my etch-a-sketch-project just completed on DOM manipulation techniques
> Add my etch-a-sketch-project

- JS101/final-project.md
> Add Brendaneus' Solution to Student Solutions

- JS101/fundamentals/rock-paper-scissors-project.md
add my solution for rock paper scissors game
> amanData solution rock paper scissors

- JS101/fundamentals/rock-paper-scissors-project.md
Add Karen Justo's solution to the rock, paper, scissors project
> Add Karen Justo solution

- JS101/final-project.md
Add my Calculator project to the javascript_curriculum
> Add my calculator project

- JS101/fundamentals/rock-paper-scissors-project.md
Add my solution to Rock, Paper, Scissors
> Add Wesley Wang's solution

- JS101/fundamentals/rock-paper-scissors-project.md
Please add my solution to the rock paper scissors project page.
Thanks!
RTV
> add RTViner's solution to rock-paper-scissors project

- JS101/fundamentals/rock-paper-scissors-project.md
I added my console Rock Paper Scissors solution to the RPS README.
> add rps solution

- JS101/fundamentals/rock-paper-scissors-project.md
Hi Admin!
Hope you're well :)
I've added a link to my solution at the bottom of the list. Thank you for taking the time to review my request!
Have a great day/night
rysergic
> Submit solution for rock paper scissors project

- JS101/fundamentals/rock-paper-scissors-project.md
Adding my solution for Rock Paper Scissors project.
> Adding Nate's RPS solution

- JS101/fundamentals/rock-paper-scissors-project.md
Hoping to get some feedback on this game.
> Adding Nixikaz's Solution

- JS101/fundamentals/rock-paper-scissors-project.md
Adding my name to the list of completed projects.
> Adding my name to the list

- organizing-js/es6-modules.md
> Fix typo in es6-modules.md

- JS101/fundamentals/rock-paper-scissors-project.md
Hello! just added my 2 solution of the Rock, Paper or Scissor game to the contribution list!
Please accept my request :smile:
Console solution: [Link](https://cobimr.github.io/webdev_101_projects/rpc-game-console/)
UI solution: [Link](https://cobimr.github.io/webdev_101_projects/rpc-game-ui/)
Happy Coding!
> Added my 2 solutions (console and UI) to the contribution list

- JS101/etch-a-sketch-project.md
Loving the course, just completed the etch-a-sketch project after much trouble and learning. This is my first pull request so please let me know if there are any issues.
> Ben Wilde etch-a-sketch solution

- JS101/etch-a-sketch-project.md
- JS101/fundamentals/rock-paper-scissors-project.md
Added my solution of Rock, Paper, Scissors project.
> Add my solution of Rock, Paper, Scissors Project

- JS101/etch-a-sketch-project.md
Added my Etch-a-Sketch solution to the page.
> add hummeldon solution

- JS101/final-project.md
Changed "you project" to "your project"
> Fixed typo in line 10

- JS101/final-project.md
Hello! just Added my solution to final project ( calculator ) on the contributors list!
> Added my solution to final project calculator

- JS101/fundamentals/rock-paper-scissors-project.md
Add Wesley Wang View In Browser link to Rock, Paper, Scissors Project
> Add Wesley Wang View In Browser Solution

- JS101/fundamentals/rock-paper-scissors-project.md
Change due to change in Github repo name. Thanks.
> Modify link to Github student solution

- JS101/fundamentals/rock-paper-scissors-project.md
#line39 - [Tadej's Solution](https://github.com/TadejPolajnar/rock-paper-scissors) - [View in Browser](https://tadejpolajnar.github.io/rock-paper-scissors/)
> Added myself under ### Student Solutions

- JS101/fundamentals/rock-paper-scissors-project.md
The link doesn't work properly as I unintentionally included a space. Hopefully this will work instead.
> Revision on Rock Paper Scissors Link

- JS101/DOM-manipulation.md
Removed apostrophe in its (line 130); added "#" for container id selector (line 138)
> Add minor corrections

- JS101/final-project.md
Here's my submission. I wanted to let y'all know, thanks for this course. This has been one of the best classes I've ever taken and one of the best things I've learned. You guys are awesome!!!
> Chris Wegscheid Submission

- JS101/fundamentals/rock-paper-scissors-project.md
Please add my solution to Lesson 5 of JavaScript Basics of Web Development 101
> Add my solution to "Rock-Paper-Scissor" project

- frameworks/frameworks-introduction.md
The previous link was not starting the video from the beginning, but from minute 11:16, a minute into the thoughts about Vue.
> Update link to frameworks comparison video

- JS101/fundamentals/rock-paper-scissors-project.md
https://github.com/jahmzu/TOP-rock-paper-scissors-game
> Jahmzu's solution!

- JS101/etch-a-sketch-project.md
Thank you so much
github : https://github.com/funtikar/EtchASketch
view on browser : https://funtikar.github.io/EtchASketch/
> Added my solution.

- JS101/fundamentals/rock-paper-scissors-project.md
Hi, i finished my UI for the Rock paper scissors project and i added my link.
> Add view in browser link

- JS101/fundamentals/rock-paper-scissors-project.md
Added View in Browser option to my solution
> update jahmzu's solution link

- JS101/final-project.md
Add link for calculator student solution in JavaScript fundamentals.
> Add student solution links

- JS101/fundamentals/rock-paper-scissors-project.md
adds my project to the rockpaperscissors-console project
> adds ajamesmichaels' project
